apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  push:
    branches:
      - '**'
jobs:
  build:
    steps:
      - name: Get source code
        uses: cloudbees-io/checkout@v1
      - name: Setup git credentials
        uses: cloudbees-io/configure-git-global-credentials@v1
      - id: build-go-binary
        name: Build Go binary
        uses: docker://golang:latest
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -tags netgo -ldflags '-w -extldflags \"-static\"' -o bdgolang --buildvcs=0
      - name: Login to AWS
        uses: cloudbees-io/configure-aws-credentials@v1
        id: aws-login
        with:
          aws-region: us-east-1
          role-to-assume: ${{ vars.oidc_staging_iam_role }}
          role-duration-seconds: "3600" # optionally set the duration of the login token
      - name: Configure container registry for AWS ECR
        uses: cloudbees-io/configure-ecr-credentials@v1
      - id: build-container
        name: Build container image
        uses: cloudbees-io/kaniko@v1
        kind: build
        with:
          destination: 020229604682.dkr.ecr.us-east-1.amazonaws.com/actions/assets-findsecbugs-scanner:qe-bdgolang
          tar-path: container-image.tar
      - id: upload-binary
        name: Upload binary using action
        uses: calculi-corp/assets-plugin-chain-utils/upload-binary@v1     
        with: 
          file-path: container-image.tar
          file-type: BINARY_CONTAINER
          debug: "true"

